# Generated by Django 3.2.9 on 2022-01-09 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='player-images')),
                ('type', models.CharField(choices=[('ALL', 'ALL'), ('BAT', 'BAT'), ('BOW', 'BOW')], default='ALL', max_length=5)),
                ('is_wk', models.BooleanField(default=False)),
                ('is_uncapped', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('foreign', models.BooleanField(default=False)),
                ('overall', models.IntegerField(default=0)),
                ('bat_ppl', models.IntegerField(default=0)),
                ('bow_ppl', models.IntegerField(default=0)),
                ('bat_mid', models.IntegerField(default=0)),
                ('bow_mid', models.IntegerField(default=0)),
                ('bat_death', models.IntegerField(default=0)),
                ('bow_death', models.IntegerField(default=0)),
                ('color', models.CharField(default='red', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='powercard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='powercards')),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='RCB', max_length=20)),
                ('room', models.IntegerField()),
                ('score', models.IntegerField(default=0, null=True)),
                ('budget', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='soldPowerCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField(default=False)),
                ('room', models.IntegerField()),
                ('powercard', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='iplbackendapi.powercard')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplbackendapi.team')),
            ],
        ),
        migrations.CreateModel(
            name='soldPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplbackendapi.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplbackendapi.team')),
            ],
        ),
    ]
