# Generated by Django 3.2.9 on 2022-01-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplbackendapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='color',
            field=models.CharField(blank=True, default='red', max_length=50, null=True),
        ),
    ]
