# Generated by Django 3.2.9 on 2022-01-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplbackendapi', '0002_alter_player_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldplayer',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
