# Generated by Django 3.2.9 on 2022-01-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplbackendapi', '0003_soldplayer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='budget',
            field=models.FloatField(default=100.0),
        ),
    ]
