# Generated by Django 3.2.9 on 2022-01-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplbackendapi', '0004_alter_team_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldplayer',
            name='playing11',
            field=models.BooleanField(default=False),
        ),
    ]
