# Generated by Django 3.2.9 on 2022-01-16 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iplbackendapi', '0005_soldplayer_playing11'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldplayer',
            name='playing11',
        ),
        migrations.CreateModel(
            name='playing11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PPL', 'PPL'), ('MID', 'MID'), ('DEATH', 'DEATH')], max_length=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplbackendapi.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplbackendapi.team')),
            ],
        ),
    ]
