# Generated by Django 3.2.9 on 2022-01-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplbackendapi', '0006_auto_20220116_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playing11',
            name='category',
        ),
    ]
