# Generated by Django 3.2.9 on 2022-01-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplbackendapi', '0007_remove_playing11_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldplayer',
            name='playing11',
            field=models.BooleanField(default=False),
        ),
    ]
