# Generated by Django 3.2.9 on 2022-02-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplbackendapi', '0008_soldplayer_playing11'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldplayer',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
