# Generated by Django 3.2.9 on 2022-02-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplbackendapi', '0009_alter_soldplayer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='playing11',
            name='room',
            field=models.IntegerField(default=-1),
        ),
    ]
