# Generated by Django 3.2.9 on 2022-03-24 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplbackendapi', '0011_auto_20220321_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldplayer',
            name='playing11',
        ),
        migrations.DeleteModel(
            name='playing11',
        ),
    ]
