# Generated by Django 4.0.3 on 2022-03-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplbackendapi', '0011_player_retainedby_alter_team_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldpowercard',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='retainedBy',
            field=models.CharField(blank=True, default='RCB', max_length=4, null=True),
        ),
    ]
