# Generated by Django 4.0.3 on 2022-03-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplbackendapi', '0012_soldpowercard_price_alter_player_retainedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldplayer',
            name='playing11',
        ),
        migrations.RemoveField(
            model_name='soldpowercard',
            name='price',
        ),
        migrations.AlterField(
            model_name='player',
            name='retainedBy',
            field=models.CharField(default='RCB', max_length=4),
        ),
        migrations.DeleteModel(
            name='playing11',
        ),
    ]
