# Generated by Django 4.0.3 on 2022-03-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplbackendapi', '0013_remove_soldplayer_playing11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldpowercard',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
